clm_homepage:
    path:     /
    defaults: { _controller: CLMBundle:Default:index }

clm_intervenant_index:
    path:     /intervenant
    defaults: { _controller: CLMBundle:Intervenant:index }

clm_apprenant_index:
    path:     /apprenant
    defaults: { _controller: CLMBundle:Apprenant:index }

clm_projet_edit:
    path:     /projet/edit/{idProjet}
    defaults: { _controller: CLMBundle:Projet:edit, idProjet: null }

clm_projet_liste:
    path:     /projet/liste
    defaults: { _controller: CLMBundle:Projet:liste }

clm_projet_details:
    path:     /projet/{idProjet}
    defaults: { _controller: CLMBundle:Projet:details, idProjet: null }

clm_equipe_edit:
    path:     /equipe/edit/{idEquipe}
    defaults: { _controller: CLMBundle:Equipe:edit, idEquipe: null }

clm_equipe_liste:
    path:     /equipe/liste
    defaults: { _controller: CLMBundle:Equipe:liste }

clm_equipe_details:
    path:     /equipe/{idEquipe}
    defaults: { _controller: CLMBundle:Equipe:details, idEquipe: null }

clm_classe_edit:
    path:     /classe/edit/{idClasse}
    defaults: { _controller: CLMBundle:Classe:edit, idClasse: null }

clm_classe_liste:
    path:     /classe/liste
    defaults: { _controller: CLMBundle:Classe:liste }

clm_classe_details:
    path:     /classe/{idClasse}
    defaults: { _controller: CLMBundle:Classe:details, idClasse: null }

clm_ticket_edit:
    path:     /ticket/edit/{idTicket}
    defaults: { _controller: CLMBundle:Ticket:edit, idTicket: null }

clm_ticket_liste:
    path:     /ticket/liste
    defaults: { _controller: CLMBundle:Ticket:liste }

clm_ticket_details:
    path:     /ticket/{idTicket}
    defaults: { _controller: CLMBundle:Ticket:details, idTicket: null }

clm_utilisateur_edit:
    path:     /utilisateur/edit/{idUtilisateur}
    defaults: { _controller: UserBundle:Utilisateur:edit, idUtilisateur: null }

clm_utilisateur_liste:
    path:     /utilisateur/liste
    defaults: { _controller: UserBundle:Utilisateur:liste }

clm_utilisateur_details:
    path:     /utilisateur/{idUtilisateur}
    defaults: { _controller: UserBundle:Utilisateur:details, idUtilisateur: null }

clm_campus_edit:
    path:     /campus/edit/{idCampus}
    defaults: { _controller: CLMBundle:Campus:edit, idCampus: null }

clm_campus_liste:
    path:     /campus/liste
    defaults: { _controller: CLMBundle:Campus:liste }

clm_campus_details:
    path:     /campus/{idCampus}
    defaults: { _controller: CLMBundle:Campus:details, idUtilisateur: null }